---
apiVersion: v1
kind: Secret
metadata:
  name: ryanj-test2-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevRHEL/ryanj-test2-frontend-gitops
